// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetAllRecentActivitiesResponse, GetCountersResponse, GetPendingResponse } from './types.gen';

export class TheDashboardResource {
    /**
     * @returns unknown Success
     * @throws ApiError
     */
    public static getAllRecentActivities(): CancelablePromise<GetAllRecentActivitiesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/api/the-dashboard/dashboard/get-all-recent-activities'
        });
    }
    
    /**
     * @returns unknown Success
     * @throws ApiError
     */
    public static getCounters(): CancelablePromise<GetCountersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/api/the-dashboard/dashboard/get-counters'
        });
    }
    
    /**
     * @returns unknown Success
     * @throws ApiError
     */
    public static getPending(): CancelablePromise<GetPendingResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/api/the-dashboard/dashboard/get-pending'
        });
    }
    
}